import { StyleSheet } from 'react-native';

export const theme = {
  primary: '#4F46E5',
  primaryLight: '#EEF2FF',
  primaryDark: '#3730A3',
  danger: '#EF4444',
  dangerLight: '#FEF2F2',
  success: '#10B981',
  successLight: '#ECFDF5',
  warning: '#F59E0B',
  warningLight: '#FFFBEB',
  bg: '#F9FAFB',
  card: '#FFFFFF',
  text: '#111827',
  textMuted: '#6B7280',
  textLight: '#9CA3AF',
  border: '#E5E7EB',
  shadow: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
};

export const styles = StyleSheet.create({
  // ── Layout ──────────────────────────────────────────
  safeArea: { flex: 1, backgroundColor: theme.bg },
  container: {
    flex: 1,
    backgroundColor: theme.card,
    paddingHorizontal: 28,
    paddingVertical: 60,
    justifyContent: 'space-between',
  },
  centerContainer: {
    flex: 1,
    backgroundColor: theme.card,
    paddingHorizontal: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  scrollContent: { paddingBottom: 100 },

  // ── Header ──────────────────────────────────────────
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 16,
    backgroundColor: theme.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  headerTitle: { fontSize: 20, fontWeight: '700', color: theme.primary },
  headerRight: { fontSize: 13, color: theme.textMuted, fontWeight: '500' },
  backBtn: { fontSize: 26, color: theme.primary, lineHeight: 30 },
  clearBtn: { fontSize: 13, color: theme.danger, fontWeight: '600' },

  // ── Typography ──────────────────────────────────────
  heroTitle: {
    fontSize: 34,
    fontWeight: '800',
    color: theme.text,
    textAlign: 'center',
    letterSpacing: -0.5,
    lineHeight: 42,
    marginBottom: 14,
  },
  heroSubtitle: {
    fontSize: 15,
    color: theme.textMuted,
    textAlign: 'center',
    lineHeight: 22,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: theme.text,
    marginBottom: 12,
    marginTop: 4,
  },

  // ── Logo ────────────────────────────────────────────
  logo: {
    fontSize: 38,
    fontWeight: '900',
    color: theme.primary,
    letterSpacing: 3,
    marginBottom: 6,
  },
  logoSmall: { fontSize: 20, fontWeight: '800', color: theme.primary, letterSpacing: 1 },
  tagline: {
    fontSize: 15,
    color: theme.textMuted,
    textAlign: 'center',
    marginBottom: 44,
    lineHeight: 22,
  },

  // ── Buttons ─────────────────────────────────────────
  btnPrimary: {
    backgroundColor: theme.primary,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    marginBottom: 16,
    ...theme.shadow,
  },
  btnPrimaryText: { color: '#fff', fontSize: 16, fontWeight: '700', letterSpacing: 0.3 },
  btnDisabled: { backgroundColor: theme.border },
  btnOutline: {
    borderWidth: 1.5,
    borderColor: theme.primary,
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
  },
  btnOutlineText: { color: theme.primary, fontSize: 16, fontWeight: '600' },

  // ── Form ────────────────────────────────────────────
  input: {
    borderWidth: 1.5,
    borderColor: theme.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    backgroundColor: theme.bg,
    color: theme.text,
    marginBottom: 12,
  },
  searchInput: {
    backgroundColor: theme.card,
    marginHorizontal: 16,
    marginVertical: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: theme.border,
    fontSize: 14,
    color: theme.text,
  },
  switchText: { color: theme.primary, textAlign: 'center', marginTop: 18, fontSize: 14, fontWeight: '500' },

  // ── Permissions ─────────────────────────────────────
  permissionCard: {
    backgroundColor: theme.bg,
    borderRadius: 18,
    padding: 8,
    marginBottom: 28,
    borderWidth: 1,
    borderColor: theme.border,
  },
  permissionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  permissionRowLast: { borderBottomWidth: 0 },
  permissionLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  permissionIcon: { fontSize: 20 },
  permissionLabel: { fontSize: 15, fontWeight: '600', color: theme.text },
  permissionSub: { fontSize: 12, color: theme.textMuted, marginTop: 1 },

  // ── Grant screen ────────────────────────────────────
  checkCircle: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: theme.success,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 28,
    ...theme.shadow,
  },
  checkEmoji: { fontSize: 42 },
  grantedCard: {
    backgroundColor: theme.successLight,
    borderRadius: 18,
    padding: 24,
    alignItems: 'center',
    marginVertical: 28,
    width: '100%',
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  grantedTitle: { fontSize: 17, fontWeight: '800', color: '#065F46', marginBottom: 8, letterSpacing: 0.5 },
  grantedDesc: { fontSize: 14, color: '#047857', textAlign: 'center', lineHeight: 20 },

  // ── Stats grid ──────────────────────────────────────
  statsGrid: { flexDirection: 'row', padding: 16, gap: 10 },
  statCard: {
    flex: 1,
    borderRadius: 18,
    padding: 16,
    alignItems: 'center',
    backgroundColor: theme.card,
    ...theme.shadow,
  },
  statIcon: { fontSize: 22, marginBottom: 6 },
  statValue: { fontSize: 26, fontWeight: '800', color: theme.text },
  statLabel: { fontSize: 10, color: theme.textMuted, marginTop: 3, fontWeight: '600', textAlign: 'center', letterSpacing: 0.3 },
  statCardBlocked: { backgroundColor: theme.warningLight },
  statCardNotif: { backgroundColor: theme.primaryLight },
  statCardSafe: { backgroundColor: theme.successLight },

  // ── Message list ─────────────────────────────────────
  messageCard: {
    backgroundColor: theme.card,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    ...theme.shadow,
  },
  avatarCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: theme.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: { fontSize: 16, fontWeight: '700', color: theme.primary },
  msgBody: { flex: 1 },
  msgSender: { fontSize: 14, fontWeight: '700', color: theme.text, marginBottom: 2 },
  msgPreview: { fontSize: 12, color: theme.textMuted, lineHeight: 17 },
  badgeSpam: {
    backgroundColor: theme.dangerLight,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeSafe: {
    backgroundColor: theme.successLight,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeSpamText: { fontSize: 11, fontWeight: '700', color: theme.danger },
  badgeSafeText: { fontSize: 11, fontWeight: '700', color: theme.success },

  // ── Settings ─────────────────────────────────────────
  settingsGroup: {
    backgroundColor: theme.card,
    borderRadius: 18,
    margin: 16,
    borderWidth: 1,
    borderColor: theme.border,
    overflow: 'hidden',
    ...theme.shadow,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  settingsRowLast: { borderBottomWidth: 0 },
  settingsIcon: { fontSize: 20, marginRight: 14 },
  settingsLabel: { flex: 1, fontSize: 15, color: theme.text, fontWeight: '500' },
  settingsChevron: { fontSize: 18, color: theme.textLight },
  logoutRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 18,
    marginHorizontal: 16,
    marginTop: 8,
    backgroundColor: theme.dangerLight,
    borderRadius: 14,
  },
  logoutText: { fontSize: 15, color: theme.danger, fontWeight: '700' },

  // ── Bottom Nav ──────────────────────────────────────
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 10,
    paddingBottom: 16,
    backgroundColor: theme.card,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  navItem: { alignItems: 'center', flex: 1, paddingTop: 4 },
  navIcon: { fontSize: 20, marginBottom: 3 },
  navLabel: { fontSize: 10, color: theme.textMuted, fontWeight: '500' },
  navLabelActive: { color: theme.primary, fontWeight: '700' },
  navDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.primary,
    marginTop: 3,
  },

  // ── Unblock button ──────────────────────────────────
  unblockBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: theme.primary,
  },
  unblockBtnText: { fontSize: 12, color: theme.primary, fontWeight: '600' },
});